//
//  OctokitListInteractor.swift
//  YatraApp
//
//  Created NMG on 16/05/20.
//  Copyright © 2020 Yatra. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreData
class OctokitListInteractor: OctokitListInteractorInputProtocol {
    
    
    private var service: ListingSevice?
    
    func fetchOctokitList() {
        if service == nil {
            service = ListingSevice(delegate: self)
        }
        service?.callAPI()
    }
    func incrementPage() {
        service?.page += 1
        service?.callAPI()
    }
    
    weak var presenter: OctokitListInteractorOutputProtocol?
}
//MARK:- ListingService Delegate
extension OctokitListInteractor: ListingSeviceDelegate {
    func service(_ service: ListingSevice, didStartFetchingListForPage page: Int) {
        presenter?.interactor(didStartFetchingListForPage: page)
    }
    
    func service(_ service: ListingSevice, didFetchList list: [UserDetailModel], forPage page: Int) {
        presenter?.interactor(didFetchList: list, forPage: page)
    }
    
    func service(_ service: ListingSevice, didFailToFetchListForPage page: Int, withError error: Error) {
        presenter?.interactor(didFailToFetchListWithError: error, page: page)
        
    }
    
    
    
    
}
