//
//  OctokitListProtocols.swift
//  YatraApp
//
//  Created NMG on 16/05/20.
//  Copyright © 2020 Yatra. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol OctokitListWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol OctokitListPresenterProtocol: class {
    var listCount: Int { get }
    func data(atIndex index: Int) -> UserDetailModel
    func viewDidLoad()
    func viewDidReachPageEnd()
    var interactor: OctokitListInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol OctokitListInteractorOutputProtocol: class {
    func interactor(didFailToFetchListWithError error: Error, page: Int)
    func interactor(didFetchList list: [UserDetailModel], forPage page : Int)
    func interactor(didStartFetchingListForPage page: Int)
    /* Interactor -> Presenter */
}

protocol OctokitListInteractorInputProtocol: class {
    
    var presenter: OctokitListInteractorOutputProtocol?  { get set }
    func fetchOctokitList()
    func incrementPage()
    /* Presenter -> Interactor */
}

//MARK: View -
protocol OctokitListViewProtocol: class {
    
    var presenter: OctokitListPresenterProtocol?  { get set }
    func showLoader(forPage page: Int)
    func hideLoader(forPage page: Int)
    func showErrorAlert(withError error: Error)
    func reloadTableview()
    
    /* Presenter -> ViewController */
}
