//
//  OctokitListRouter.swift
//  YatraApp
//
//  Created NMG on 16/05/20.
//  Copyright © 2020 Yatra. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OctokitListRouter: OctokitListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = OctokitListViewController(nibName: nil, bundle: nil)
        let interactor = OctokitListInteractor()
        let router = OctokitListRouter()
        let presenter = OctokitListPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
